from fpdf import FPDF
from fpdf.enums import XPos, YPos
from datetime import datetime
import uuid

class MedicalReport(FPDF):
    def header(self):
        # Professional Header
        self.set_font("helvetica", "B", 16)
        self.cell(0, 12, text="MEDICAL AI SUITE", new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C")
        self.set_font("helvetica", "I", 10)
        self.cell(0, 8, text="AI-Assisted Clinical Diagnostic Report", new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C")
        self.ln(2)
        self.set_draw_color(0, 0, 0)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-20)
        self.set_font("helvetica", "I", 8)
        self.cell(0, 5, f"Page {self.page_no()} | Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", align="C")
        self.ln(3)
        self.cell(0, 5, "This report is generated by AI and should be reviewed by a qualified clinician.", align="C")

    def add_explanation_section(self, pos_factors, neg_factors):
        """
        Handles the visual plot and the textual explanation for any model type.
        """
        self.set_font("helvetica", "B", 14)
        self.cell(0, 10, text="DIAGNOSTIC INSIGHTS & EXPLAINABILITY", 
                  new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        
        # 2. The Textual Impact Analysis
        self.set_font("helvetica", "B", 12)
        
        # Positive Contributors (Increasing Risk)
        if pos_factors:
            self.set_text_color(200, 0, 0) # Red
            self.cell(0, 8, text="Primary Risk Drivers:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            self.set_text_color(0, 0, 0) # Reset to black
            self.set_font("helvetica", size=10)
            for factor in pos_factors:
                self.cell(0, 6, text=f"- {factor}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            self.ln(2)

        # Negative Contributors (Protective Factors)
        if neg_factors:
            self.set_font("helvetica", "B", 12)
            self.set_text_color(0, 128, 0) # Green
            self.cell(0, 8, text="Key Protective Factors:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            self.set_text_color(0, 0, 0)
            self.set_font("helvetica", size=10)
            for factor in neg_factors:
                self.cell(0, 6, text=f"- {factor}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

def create_report(patient_name, disease, result, probability, patient_features=None, feature_names=None, 
                 feature_ranges=None, feature_impacts=None, pos_factors=None, neg_factors=None, audited_report=None):
    """
    Enhanced medical report with administrative data, vital signs grid, and explainability.
    
    Args:
        patient_name: Patient name
        disease: Disease category
        result: Prediction result text
        probability: Model confidence percentage
        patient_features: List of patient feature values
        feature_names: List of human-readable feature names
        feature_ranges: Dict with feature names as keys and (normal_range, unit) as values
        feature_impacts: Dict with feature names as keys and impact scores as values
    """
    pdf = MedicalReport()
    pdf.add_page()

    # === ADMINISTRATIVE HEADER ===
    pdf.set_font("helvetica", "B", 11)
    pdf.cell(0, 8, text="REPORT METADATA", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    report_id = str(uuid.uuid4())[:8].upper()
    pdf.set_font("helvetica", size=10)
    pdf.cell(0, 6, text=f"Report ID: {report_id}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 6, text=f"Generated: {datetime.now().strftime('%B %d, %Y at %H:%M:%S')}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(3)

    # === PATIENT & DIAGNOSIS INFO ===
    pdf.set_font("helvetica", "B", 11)
    pdf.cell(0, 8, text="PATIENT INFORMATION", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("helvetica", size=10)
    pdf.cell(0, 6, text=f"Patient Name: {patient_name}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 6, text=f"Diagnosis Category: {disease}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(3)

    # === DIAGNOSTIC ASSESSMENT ===
    pdf.set_font("helvetica", "B", 11)
    pdf.cell(0, 8, text="DIAGNOSTIC ASSESSMENT", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    
    if "High Risk" in result or "Detected" in result:
        pdf.set_text_color(200, 0, 0)
    else:
        pdf.set_text_color(0, 150, 0)
    
    pdf.set_font("helvetica", "B", 11)
    pdf.cell(0, 8, text=f"Conclusion: {result}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_text_color(0, 0, 0)
    
    # === VITAL SIGNS / INPUT RECAP TABLE ===
    if patient_features and feature_names:
        pdf.set_font("helvetica", "B", 11)
        pdf.cell(0, 8, text="INPUT PATIENT DATA & REFERENCE RANGES", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        
        pdf.set_font("helvetica", size=9)
        col_width = 65
        
        # Table header
        pdf.set_fill_color(200, 200, 200)
        pdf.cell(col_width, 6, "Feature", border=1, fill=True)
        pdf.cell(40, 6, "Patient Value", border=1, fill=True)
        pdf.cell(60, 6, "Reference Range", border=1, fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        
        # Table rows
        pdf.set_fill_color(240, 240, 240)
        for i, fname in enumerate(feature_names):
            if i < len(patient_features):
                value = patient_features[i]
                range_info = feature_ranges.get(fname, "N/A") if feature_ranges else "N/A"
                
                pdf.cell(col_width, 6, str(fname)[:35], border=1)
                pdf.cell(40, 6, str(value)[:12], border=1)
                pdf.cell(60, 6, str(range_info)[:35], border=1, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        
        pdf.ln(5)

# --- TEXTUAL IMPACT ANALYSIS SECTION ---
    if pos_factors or neg_factors:
        # 1. Clear Section Header
        pdf.ln(5)
        pdf.set_font("helvetica", "B", 14)
        pdf.cell(0, 10, text="Diagnostic Insights & Risk Analysis", 
                new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_draw_color(200, 200, 200)
        pdf.line(pdf.get_x(), pdf.get_y(), pdf.get_x() + 190, pdf.get_y())
        pdf.ln(2)

        # 2. Risk Drivers (Positive SHAP)
        if pos_factors:
            pdf.set_font("helvetica", "B", 12)
            pdf.set_text_color(200, 0, 0) # Red
            pdf.cell(0, 10, text="Primary Risk Drivers:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.set_font("helvetica", size=10)
            pdf.set_text_color(0, 0, 0)
            for factor in pos_factors:
                # Adding a bullet point icon for professional look
                pdf.cell(0, 7, text=f"  > {factor}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.ln(2)

        # 3. Protective Factors (Negative SHAP)
        if neg_factors:
            pdf.set_font("helvetica", "B", 12)
            pdf.set_text_color(0, 128, 0) # Green
            pdf.cell(0, 10, text="Key Protective Factors:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.set_font("helvetica", size=10)
            pdf.set_text_color(0, 0, 0)
            for factor in neg_factors:
                pdf.cell(0, 7, text=f"  > {factor}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # 3. Clinical Note
    pdf.ln(10)
    pdf.set_font("helvetica", "I", 9)
    pdf.multi_cell(0, 5, text="Note: These factors are identified using SHAP explainability analysis. "
                                "Drivers indicated with [!] pushed the risk score higher, while factors "
                                "marked with [+] helped lower the final risk assessment.")                
    
    if audited_report:
        pdf.ln(8)
        pdf.set_font("helvetica", "B", 12)
        pdf.cell(0, 8, text="RAG-Audited Clinical Guidance", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_font("helvetica", size=10)
            
        report_text = str(audited_report)
        replacements = {
            "\u2013": "-",  # En-dash
            "\u2014": "-",  # Em-dash
            "\u2018": "'",  # Left single quote
            "\u2019": "'",  # Right single quote
            "\u201c": '"',  # Left double quote
            "\u201d": '"',  # Right double quote
            "\u2022": "*",  # Bullet point mark
        }
        for bad_char, good_char in replacements.items():
            report_text = report_text.replace(bad_char, good_char)
                
    # 2. Strict fallback safety net to catch any other unsupported tokens
    cleaned_report = report_text.encode('latin-1', 'ignore').decode('latin-1')
        
    # 3. Print the safe string
    pdf.multi_cell(0, 6, text=cleaned_report)
    
    # === CLINICIAN SIGNATURE ===
    pdf.set_font("helvetica", "B", 11)
    pdf.cell(0, 8, text="CLINICIAN REVIEW & SIGNATURE", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("helvetica", size=10)
    pdf.cell(0, 6, text="Clinician Name (Print): _____________________________", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.cell(0, 6, text="Signature: ________________________  Date: _________", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(5)



# 1. FORCE a clean break and drop down vertically by 10 units
    pdf.ln(10)  

    # 2. Re-establish explicit positioning flags on the multi_cell layout
    

    pdf.multi_cell(
        w=0,  # Now correctly spans the entire width from left to right margins
        h=5,  # Slightly relaxed line height for readability
        text=(
            "DISCLAIMER: This report is generated by artificial intelligence for educational and demonstration purposes only. "
            "It must NOT be used as a substitute for professional medical advice, diagnosis, or treatment. "
            "A licensed clinician must review and validate all findings before any clinical decision-making."
        ),
        new_x=XPos.LMARGIN,  # CRITICAL: Snaps the cursor position back to the left margin
        new_y=YPos.NEXT      # CRITICAL: Forces the cursor to drop to a fresh line afterward
    )
    # Return the PDF as bytes so Streamlit can handle the download
    return bytes(pdf.output(dest='S'))